site_name: 5s - Computação Embarcada
theme:
  name: 'material'
  palette:
    primary: 'black'
    accent: 'pink'
  font:
    text: Roboto
    code: Roboto Mono

docs_dir: docs-src
site_dir: docs

repo_name: 'Insper/ComputacaoEmbarcada'
repo_url: 'https://github.com/insper/ComputacaoEmbarcada'
edit_uri: 'https://github.com/Insper/ComputacaoEmbarcada/edit/master/docs-src/'

# Copyright
copyright: 'Copyright &copy; Rafael Corsi @ insper'

nav:
- Home: index.md
- Sobre-Curso.md
- 'SAME70-Examples': 'https://github.com/Insper/SAME70-examples'
- 'Vídeos': Util-Videos.md
- 'Util':
    - Sobre-Ferramental.md
    - Util-Startup.md
    - Util-Erros.md
    - 'Util-Documentos.md'

- Dicas:
    - 'Lab-1-IOs-Dicas.md'
    - 'Util-lcd.md'
    - 'Util-freertos.md'
    - 'Util-FloatPrint.md'
    - 'Util-lvgl.md' 

- Labs:
    - 'Lab 1 - PIO ':
      - 'Teoria': 'Lab_PIO/Lab-PIO-Teoria.md'
      - 'Lab': 'Lab_PIO/Lab-PIO.md'
 #     - 'PIO - Perguntas': 'Lab-1-IOs-Perguntas.md'
    - 'Lab 2 - PIO - Driver':
      - 'Teoria': 'Lab_DRIVER/Lab-PIO-DRIVER-Teoria.md'
      - 'Lab': 'Lab_DRIVER/Lab-PIO-DRIVER.md'
    - 'Lab 3 - PIO - IRQ':
      - 'Teoria': 'Lab_PIO_IRQ/Lab-PIO-IRQ-Teoria.md'
      - 'Lab' : 'Lab_PIO_IRQ/Lab-PIO-IRQ.md'
 #     - 'Lab-3-PIO-IRQ-Perguntas.md'
    - 'Lab 4 - TC - RTC - RTT': 'Lab_TC_RTC_RTT/Lab-TC-RTC-RTT.md'
    - 'Lab 5 - RTOS':
       - 'Lab': 'Lab_RTOS/Lab-RTOS.md'
       - 'Dicas': 'Lab_RTOS/Lab-RTOS-dicas.md'
    - 'Lab 6 - RTOS - ADC': 'Lab_RTOS_ADC/Lab-RTOS-ADC.md'
    - 'Lab 7 - RTOS - LCD - LVGL':
        - 'Lab_RTOS_LCD_LVGL/Lab-RTOS-LCD-LVGL-START.md'
        - 'Lab_RTOS_LCD_LVGL/Lab-RTOS-LCD-LVGL-LAB.md'
    - 'Lab 8 - ECG': 'Lab_ECG/Lab-ECG.md'
#    - 'Lab-9-ADC-FIR.md'
#    - 'Lab-8-RTOS-UART.md'
#    - 'Lab-10-RTOS-WIFI.md'

- Projeto:
#    - 'Projeto 1':
        - 'Descrição': 'Projeto-1-Descricao.md'
#        - 'Vending Machine': 'https://github.com/Insper/ComputacaoEmbarcada/blob/master/Projeto%201/Folder-VendingMachine.pdf'
        - 'Controle': 'https://github.com/Insper/ComputacaoEmbarcada/blob/master/Projeto%201/Folder-controle.pdf'
        - 'Handout 1':  'https://app.mural.co/t/elementos9119/m/elementos9119/1616424619557/3341fbe703cab0b531da459548f0124af1af1669'
#        - 'Dicas': 'Projeto-1-Dicas.md'
        - 'Projeto-1-Rubrica.md'
        - 'Projeto-1-Dicas.md'
        - 'Projeto-1-Lista.md'
#    - 'Projeto 2':
#        - 'Descrição': 'Projeto-2-Descrição.md'
#        - 'Projeto-2-Lista.md'

- APS:
    - 'APS-howto.md'
    - 'APS 1 - Musical':
        - 'APS-1-Musical.md'
        - 'APS-1-Musical-software.md'
    - 'APS-2-Oximetro.md'
#    - 'APS-3-IoT.md'

- Avaliações e Simulados: 'Avaliacoes.md'
#    - '20b/AV1.md'
#    - 'AV0 Simulado': 'AV-0-Simulado.md'
#    - 'AV0 Prática': 'AV-0.md'
#    - 'AV1 Simulado': 'AV-1-Simulado.md'
#    - 'AV1 Prática': 'AV-1.md'

#####################################################################
#extra_css:
#  - css/printing.css
#  - css/progress.css

extra_javascript:
  - https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.0/MathJax.js?config=TeX-MML-AM_CHTML
  - https://www.gstatic.com/firebasejs/8.4.3/firebase-app.js
  - https://www.gstatic.com/firebasejs/8.4.0/firebase-database.js
  - https://cdnjs.cloudflare.com/ajax/libs/js-yaml/4.0.0/js-yaml.min.js
  - js/markdown-enhancer.js
#  - 'js/dom-confetti.js'
#  - 'js/progress.js'

# Extensions
markdown_extensions:
  - markdown.extensions.attr_list
  - markdown.extensions.admonition
  - markdown.extensions.codehilite:
      guess_lang: false
  - markdown.extensions.def_list
  - markdown.extensions.footnotes
  - markdown.extensions.meta
  - markdown.extensions.toc:
      permalink: true
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink:
      repo_url_shorthand: true
      user: squidfunk
      repo: mkdocs-material
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tabbed
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

plugins:
  - git-revision-date-localized
  - search
