theme:
  name: active-handout-theme

docs_dir: docs-src
site_dir: docs
site_name: 5s - Computação Embarcada
repo_name: "Insper/ComputacaoEmbarcada"
repo_url: "https://github.com/insper/ComputacaoEmbarcada"
edit_uri: "https://github.com/Insper/ComputacaoEmbarcada/edit/master/docs-src/"
copyright: "Copyright &copy; Rafael Corsi @ insper"

extra_javascript:
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

plugins:
  - active-handout:
      telemetry: true
      backend_url: http://localhost:8080/api/
      course_slug: 22b Embarcados

markdown_extensions:
  - markdown.extensions.admonition
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.details
  - pymdownx.tabbed
  - pymdownx.superfences
  - pymdownx.magiclink
  - pymdownx.critic:
      mode: view
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.smartsymbols
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
  - attr_list

#####################################################################

nav:
  - Home: "index.md"
  - Sobre o curso: "Sobre-Curso.md"
  - SAME70-Examples: "https://github.com/Insper/SAME70-examples"
  - Vídeos: "navigation/Videos/Util-Videos.md"
  - navigation/Dicas/Util-o-que-nao-pode.md
  - Util:
      - navigation/Util/Sobre-Ferramental.md
      - navigation/Util/Util-Startup.md
      - navigation/Util/Util-Erros.md
      - navigation/Util/Util-Documentos.md
      - navigation/Dicas/Util-lcd.md
      - navigation/Dicas/Util-freertos.md
      - navigation/Dicas/Util-FloatPrint.md
      - navigation/Dicas/Util-lvgl.md
  - Labs:
      - "Lab 1 - PIO ":
          - "Teoria": "navigation/Labs/Lab_PIO/Lab-PIO-Teoria.md"
          - "Lab": "navigation/Labs/Lab_PIO/Lab-PIO.md"
          - "Dicas": navigation/Dicas/Lab-PIO-Dicas.md
      - "Lab 2 - PIO - Driver":
          - "Teoria": "navigation/Labs/Lab_PIO_DRIVER/Lab_PIO_DRIVER-Teoria.md"
          - "Lab": "navigation/Labs/Lab_PIO_DRIVER/Lab_PIO_DRIVER.md"
      - "Lab 3 - PIO - IRQ":
          - "Teoria": "navigation/Labs/Lab_PIO_IRQ/Lab-PIO-IRQ-Teoria.md"
          - "Lab": "navigation/Labs/Lab_PIO_IRQ/Lab-PIO-IRQ.md"
          - "Praticando": "navigation/Labs/Lab_PIO_IRQ/Lab-PIO-IRQ-pratica.md"
      - "Lab 4 - RTOS":
          - "Lab": "navigation/Labs/Lab_RTOS/Lab-RTOS.md"
          - "Teoria": "navigation/Labs/Lab_RTOS/Teoria.md"
      - "Lab 5 - RTOS HC-SR04": "navigation/Labs/Lab_RTOS_HCSR04/lab.md"
      - "Lab 6 - RTOS IMU": "navigation/Labs/Lab_RTOS_imu/lab.md"
      - "Lab 7 - RTOS - LCD - LVGL":
          - "navigation/Labs/Lab_RTOS_LCD_LVGL/Lab-RTOS-LCD-LVGL-START.md"
          - "navigation/Labs/Lab_RTOS_LCD_LVGL/Lab-RTOS-LCD-LVGL-LAB.md"
          - "navigation/Labs/Lab_RTOS_LCD_LVGL/Lab-RTOS-LCD-LVGL-LAB2.md"
      - "Lab 8 - TC - RTC - RTT": "navigation/Labs/Lab_TC_RTC_RTT/Lab-TC-RTC-RTT.md"
      - "Lab 9 - RTOS - Mutex": navigation/Labs/Lab_mutex/lab.md
      - "Lab 10 - WIFI": "navigation/Labs/Lab_RTOS_WIFI/Lab-RTOS-WIFI.md"
  - Labs extras:
      - 'RTOS - ADC': 'navigation/Labs/Lab_RTOS_ADC/Lab-RTOS-ADC.md'
      - 'ECG': 'navigation/Labs/Lab_ECG/Lab-ECG.md'
      - 'navigation/Labs/Lab_ADC_FIR/Lab-ADC-FIR.md'
      - 'navigation/Labs/Lab_RTOS_UART/Lab-RTOS-UART.md'
  - Projeto:
      - "Descrição": "navigation/Projeto/Projeto-1-Descricao.md"
      - navigation/Projeto/Projeto-1-Dispositivos.md
      - navigation/Projeto/Projeto-1-Entrega1.md
      - navigation/Projeto/Projeto-1-Entrega3.md
      - navigation/Projeto/Projeto-1-Dicas.md
      - navigation/Projeto/vjoy.md
      - navigation/Projeto/Projeto-1-Lista.md
  - APS:
      - "APS 1 - Musical":
          - "navigation/APS/APS-1-Musical.md"
          - "navigation/APS/APS-1-Musical-software.md"
      - "APS 2 - Ciclocomputador":
          - "navigation/APS/APS-2-Bike/Descricao.md"
          - "navigation/APS/APS-2-Bike/Design.md"
          - "navigation/APS/APS-2-Bike/Engenharia.md"
          - "navigation/APS/APS-2-Bike/Rubrica.md"
  #    - 'navigation/APS/APS-2-Oximetro.md'
  #    - 'navigation/APS/APS-3-IoT.md'
  - Avaliações e Simulados:
      - "Avaliação síncrona": navigation/Avaliacoes_e_Simulados/Avaliacoes.md
      - "Avaliação assíncrona": navigation/Prova_assincrona/index.md

extra:
  custom_variables:
    lab01_deadline: "15/02/2023 - 23h59"
    lab02_deadline: "22/02/2023 - 23h59"
    lab03_deadline: "08/03/2023 - 23h59"
    lab04_deadline: "15/03/2023 - 23h59"
    lab05_deadline: "22/03/2023 - 23h59"
    lab06_deadline: "29/03/2023 - 23h59"
    lab07_deadline: "26/04/2023 - 23h59"
    lab08_deadline: "03/05/2023 - 23h59"
    lab09_deadline: "10/05/2023 - 23h59"
    lab10_deadline: "17/05/2023 - 23h59"
    aps1_deadline: "11/03/2023 - 23h59"
    aps1_classroom: https://classroom.github.com/a/DR7U66AC
    aps1_entrega: "Via blackboard"
