site_name: Embarcados Avançados
theme:
  feature:
    tabs: true
  name: 'material'
  palette:
      primary: 'deep purple'
      accent: 'pink'
  logo:
      icon: 'developer_board'
  font:
    text: Roboto
    code: Roboto Mono

docs_dir: docs-src
site_dir: docs

repo_name: 'Insper/ComputacaoEmbarcada'
repo_url: 'https://github.com/insper/ComputacaoEmbarcada'
edit_uri: 'https://github.com/Insper/ComputacaoEmbarcada/edit/master/docs-src/'

nav:
- Home: index.md
- Sobre: Sobre.md
- 'SAME70-Exmamples': 'https://github.com/Insper/SAME70-examples'
- Projetos:
    - 'Projeto 1 - Descrição': 'Projeto-1-Descrição.md'
    - 'Projeto 1 - Vending Machine': 'Projeto-1-Vending-Machine.md'
    - 'Projeto 1 - Controle': 'Projeto-1-Controle.md'
- APS:
    - 'APS 1 - Musical': 'APS-1-Musical.md'
    - 'APS 2 - Interface':
        - 'Geral': 'APS-2-Interface.md'
        - 'Design': 'APS-2-Interface-Design.md'
        - 'Engenharia': 'APS-2-Interface-Engenharia.md'
        - 'Dicas': 'APS-2-Interface-Dicas.md'
- Avaliações:
    - 'AV0 Simulado': 'AV-0-Simulado.md'
    - 'AV0 Pratica': 'AV-0.md'
- Labs:
    - 'Lab 1 - IOs':
        - 'Teoria': 'Lab-1-IOs-Teoria.md'
        - 'Lab': 'Lab-1-IOs-Lab.md'
        - 'Dicas': 'Lab-1-IOs-Dicas.md'
        - 'Perguntas': 'Lab-1-IOs-Perguntas.md'
    - 'Lab 2 - PIO driver':
        - 'Teoria': 'Lab-2-PIO-Driver-Teoria.md'
        - 'Lab': 'Lab-2-PIO-Driver-Teoria.md'
    - 'Lab 3 - PIO IRQ':
        - 'Teoria': 'Lab-3-PIO-IRQ-Teoria.md'
        - 'Lab': 'Lab-3-PIO-IRQ-Lab.md'
        - 'Perguntas': 'Lab-3-PIO-IRQ-Perguntas.md'
    - 'Lab 4 - TC e RTC': 'Lab-4-TickTack-Lab.md'
    - 'Lab 5 - ADC': 'Lab-5-ADC.md'

# Extensions
markdown_extensions:
  - markdown.extensions.admonition
  - markdown.extensions.codehilite:
      guess_lang: false
  - markdown.extensions.def_list
  - markdown.extensions.footnotes
  - markdown.extensions.meta
  - markdown.extensions.toc:
      permalink: true
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink:
      repo_url_shorthand: true
      user: squidfunk
      repo: mkdocs-material
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
plugins:
    - search
#    - pdf-export
