theme:
  name: active-handout-theme

docs_dir: docs-src
site_dir: docs
site_name: 5s - Computação Embarcada
repo_name: "Insper/ComputacaoEmbarcada"
repo_url: "https://github.com/insper/ComputacaoEmbarcada"
edit_uri: "https://github.com/Insper/ComputacaoEmbarcada/edit/master/docs-src/"
copyright: "Copyright &copy; Rafael Corsi @ insper"

extra_javascript:
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

plugins:
  - glightbox
  - active-handout:
      telemetry: true
      backend_url: http://localhost:8080/api/
      course_slug: 22b Embarcados
      plugin_exercise_counter: false

markdown_extensions:
  - footnotes
  - markdown.extensions.admonition
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.details
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.superfences
  - pymdownx.magiclink
  - pymdownx.critic:
      mode: view
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.smartsymbols
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
  - attr_list

#####################################################################

nav:
  - Home: "index.md"
  - Sobre o curso: "Sobre-Curso.md"
  - SAME70-Examples: "https://github.com/Insper/SAME70-examples"
  - Vídeos: "navigation/Videos/Util-Videos.md"
  - Util:
      - Notas: navigation/Util/Util-Notas.md
      - Ferramental: navigation/Util/Sobre-Ferramental.md
      - Bring up: navigation/Util/Util-Startup.md
      - Erros comum: navigation/Util/Util-Erros.md
      - Manuais: navigation/Util/Util-Documentos.md
      - LCD max Touch: navigation/Dicas/Util-lcd.md
      - Freertos: navigation/Dicas/Util-freertos.md
      - Float Point (SAM): navigation/Dicas/Util-FloatPrint.md
      - LVGL: navigation/Dicas/Util-lvgl.md
  - Labs:
      - "Lab 1 - PIO ":
          - "Teoria": "navigation/Labs/Lab_PIO/Lab-PIO-Teoria.md"
          - "Lab": "navigation/Labs/Lab_PIO/Lab-PIO.md"
          - "Dicas": navigation/Dicas/Lab-PIO-Dicas.md
      - "Lab 2 - PIO - Driver":
          - "Teoria": "navigation/Labs/Lab_PIO_DRIVER/Lab_PIO_DRIVER-Teoria.md"
          - "Lab": "navigation/Labs/Lab_PIO_DRIVER/Lab_PIO_DRIVER.md"
      - "Lab 3 - PIO - IRQ":
          - "Teoria": "navigation/Labs/Lab_PIO_IRQ/Lab-PIO-IRQ-Teoria.md"
          - "Lab - Parte 1": "navigation/Labs/Lab_PIO_IRQ/Lab-PIO-IRQ.md"
          - "Lab - Parte 2": "navigation/Labs/Lab_PIO_IRQ/Lab-PIO-IRQ-pratica.md"
      - "Lab 4 - RTOS":
          - "Lab": "navigation/Labs/Lab_RTOS/Lab-RTOS.md"
          - "Teoria": "navigation/Labs/Lab_RTOS/Teoria.md"
      - "Lab 5 - RTOS HC-SR04": "navigation/Labs/Lab_RTOS_HCSR04/Lab_RTOS_HCSR04.md"
      - "Lab 6 - RTOS IMU": "navigation/Labs/Lab_RTOS_IMU/Lab_RTOS_IMU.md"
      - "Lab 7 - RTOS - LCD - LVGL":
          - navigation/Labs/Lab_RTOS_LCD_LVGL/Lab-RTOS-LCD-LVGL-START.md
          - navigation/Labs/Lab_RTOS_LCD_LVGL/Lab-RTOS-LCD-LVGL-LAB.md
          - navigation/Labs/Lab_RTOS_LCD_LVGL/Lab-RTOS-LCD-LVGL-LAB2.md
      - "Lab 8 - TC - RTC - RTT": "navigation/Labs/Lab_TC_RTC_RTT/Lab-TC-RTC-RTT.md"
      - "Lab 9 - RTOS - Mutex": navigation/Labs/Lab_RTOS_MUTEX/Lab_RTOS_MUTEX.md
      - "Lab 10 - WIFI": "navigation/Labs/Lab_RTOS_WIFI/Lab-RTOS-WIFI.md"
  - Labs extras:
      - 'RTOS - ADC': 'navigation/Labs/Lab_RTOS_ADC/Lab-RTOS-ADC.md'
      - 'ECG': 'navigation/Labs/Lab_ECG/Lab-ECG.md'
      - 'navigation/Labs/Lab_ADC_FIR/Lab-ADC-FIR.md'
      - 'navigation/Labs/Lab_RTOS_UART/Lab-RTOS-UART.md'
  - Projeto:
      - Descrição: "navigation/Projeto/Projeto-1-Descricao.md"
      - Dispositivos: navigation/Projeto/Projeto-1-Dispositivos.md
      - Entrega 1: navigation/Projeto/Projeto-1-Entrega1.md
      - Entrega 2: navigation/Projeto/Projeto-1-Entrega3.md
      - Dicas: navigation/Projeto/Projeto-1-Dicas.md
      - Vjoy: navigation/Projeto/vjoy.md
      - Anteriores: navigation/Projeto/Projeto-1-Lista.md
  - APS:
      - "APS 1 - Musical":
          - Descritivo: "navigation/APS/APS-1-Musical.md"
          - Firmware: "navigation/APS/APS-1-Musical-software.md"
      - "APS 2 - Ciclocomputador":
          - "navigation/APS/APS-2-Bike/Descricao.md"
          - "navigation/APS/APS-2-Bike/Design.md"
          - "navigation/APS/APS-2-Bike/Engenharia.md"
          - "navigation/APS/APS-2-Bike/Rubrica.md"
  #    - 'navigation/APS/APS-2-Oximetro.md'
  #    - 'navigation/APS/APS-3-IoT.md'
  - Avaliações e Simulados:
      - "Avaliação síncrona": navigation/Avaliacoes_e_Simulados/Avaliacoes.md
      - "Avaliação assíncrona": navigation/Prova_assincrona/index.md

  - Code quality:
      - Visão geral: navigation/CodeQuality/topview.md
      - Regras: navigation/CodeQuality/rules.md
      - Cppcheck: navigation/CodeQuality/cppcheck.md
      - Variáveis: navigation/CodeQuality/variables.md
      - Head File: navigation/CodeQuality/head-file.md
      - ISR - variáveis: navigation/CodeQuality/isr-variables.md
      - ISR - handler: navigation/CodeQuality/isr-handler.md

extra:
  custom_variables:
    rules_variables_classroom: https://classroom.github.com/a/_abubHkm
    rules_isr_volatile_classroom: https://classroom.github.com/a/_wYWDjs0
    rules_isr_classroom: https://classroom.github.com/a/VfTjqXBK
    rules_cppcheck_classroom: https://classroom.github.com/a/iFm3FeF8
    rules_head_classroom: https://classroom.github.com/a/OryPvQ6Z

    lab01_deadline: 23/08/2023
    lab01_classroom: https://classroom.github.com/a/xzPCYyFH
    lab01_forms: https://docs.google.com/forms/d/e/1FAIpQLSfva4jkYdpGOZpjnTeXfHVBH50gg6ALzIm6hKr_qarQbfwT6A/viewform?usp=sf_link
    
    lab02_deadline: 28/08/2023
    lab02_classroom: https://classroom.github.com/a/4SaxPGpR
    lab02_forms: https://docs.google.com/forms/d/e/1FAIpQLSen3YNQLkLTwOyIrDlb9rFiedmzGJT__-PMCz56R_zIsXVGxg/viewform?usp=sf_link
    
    lab03_deadline: 04/09/2023
    lab03_parte_1_classroom: https://classroom.github.com/a/piGR02zw
    lab03_parte_2_classroom: https://classroom.github.com/a/fS0CVR5G
    lab03_forms: https://docs.google.com/forms/d/e/1FAIpQLSe68Mm0pKsKaHZ2xG2Qudt6-cGh9uANtetEFiAaQYZT72wJKA/viewform?usp=sf_link
    
    lab04_deadline: 18/09/2023
    lab04_classroom: https://classroom.github.com/a/NWVEQ7qy
    lab04_forms: https://docs.google.com/forms/d/e/1FAIpQLSf2g5mffnCr-oKitRwtReG-T4sotSslGx0Bi9O8spNya8HYKw/viewform?usp=sf_link
    
    lab05_deadline: 27/09/2023
    lab05_classroom: https://classroom.github.com/a/O_QUCkpb

    lab06_deadline: 04/10/2023
    lab06_classroom: https://classroom.github.com/a/SZy1p43k
    lab06_forms: https://docs.google.com/forms/d/e/1FAIpQLSfP17TGajFhBJKYbc1evZQb3IWQCRP2k33caTekqjqNdJThCg/viewform?usp=sf_link
    
    lab07_deadline: 16/11/2023
    lab07_classroom: https://classroom.github.com/a/Rl7NKjIh
    lab07_forms: https://docs.google.com/forms/d/e/1FAIpQLSdaItc1IebfgUT0CikaDpcl88EmF9WpkJmYE4ZTr63R7Vbzzw/viewform?usp=sf_link
    
    lab08_deadline: 13/11/2023
    lab08_classroom: TBD
    lab08_forms: https://docs.google.com/forms/d/e/1FAIpQLScx-alJICVPLDiV9tf_gAUZCRmYkU5XC5L0kH5MUq3jnFMGAQ/viewform?usp=sf_link
    
    lab09_deadline: 16/11/2023
    lab09_classroom: TBD
    lab09_forms: https://docs.google.com/forms/d/e/1FAIpQLSfOJ6DV4S0LzTYYHppSZgqKTulsjRJZYK7cGtg2YBefDcWbig/viewform?usp=sf_link
    
    lab10_deadline: 20/11/2023
    lab10_classroom: TBD
    lab10_forms: https://docs.google.com/forms/d/e/1FAIpQLSfvFItKYSinY_UWisMpkRlyXRvn7hqGsTqpLtieJF3phdU8LQ/viewform?usp=sf_link
    
    aps1_deadline: 09/09/2023
    aps1_classroom: https://classroom.github.com/a/VFRkr4Ac
    aps1_forms: https://docs.google.com/forms/d/e/1FAIpQLSds7AUasDkBcZ3ykMfivzMwWqzPFscJXPiZcZ0B_0FBElYNHw/viewform?usp=sf_link

    proj_idealizacao_deadline: 29/09/2023
    proj_deadline: 14/10/2023
    proj_mural: https://app.mural.co/t/elementos9119/m/elementos9119/1694982355553/181c6f198f54bc2884c19440965d09789dd6478e?sender=ub569a9273c6e285461187641
    proj_classroom: https://classroom.github.com/a/usPA3Ye8
    proj_forms: TBD

    proj_entrega2_prototipo_deadline: 29/09/2023
    proj_entrega2_prototipo_classroom: https://classroom.github.com/a/usPA3Ye8
    proj_entrega2_forms: https://docs.google.com/forms/d/e/1FAIpQLSftJoG-P8IRc8FXwSZSN7KLL_kq0ixdFjQGzYE6d30MZsdegA/viewform?usp=sf_link

    aps2_classroom: https://classroom.github.com/a/dWfahYIz
    aps2_mural: https://app.mural.co/t/elementos9119/m/elementos9119/1699886697816/45e6c066de613a01b3d8ce1cd0425413e4a25b28?sender=ub569a9273c6e285461187641
    aps2_forms: TBD
    aps2_deadline_design: 24/11/2023
